#!/usr/bin/env python
"""
File Description: File used for definition of plan plotting functions.
"""

# ******************************************    Libraries to be imported    ****************************************** #
from ipyhop.graph_utils import DiGraph, dfs_preorder_nodes


# ****************************************        Function Declaration        **************************************** #
def planar_plot(graph: DiGraph, root_node: int = 0):
    """
    *   planar_plot(graph, root_node=0) tells IPyHOP to create a planar plot of the graph.
        This can be used to visualize the solution planning graph.
        Solution planning graph can be accessed using planner.sol_tree.

    Note: matplotlib has been removed as a dependency. This function now returns
    without visualization. Use print_tree() for text-based visualization instead.

    :param graph: A planning graph generated by IPyHOP.
    :param root_node: The node to use as a root node. If any node other than 0 (0 is always the root)
        is used as root_node then only the subgraph from that node is plotted.
    """
    node_list = list(dfs_preorder_nodes(graph, root_node))

    # Build node information for text output
    print("Planning Tree Visualization (Text Mode)")
    print("=" * 60)
    print(f"Root node: {root_node}")
    print(f"Total nodes in subgraph: {len(node_list)}")
    print("-" * 60)

    for i, node in enumerate(node_list):
        node_info = graph.nodes[node]
        node_type = node_info.get("type", "?")
        node_data = node_info.get("info", "")

        # Determine indentation based on node type
        type_colors = {
            "D": "Decision",
            "T": "Task",
            "G": "Goal",
            "M": "MultiGoal",
            "A": "Action",
            "VG": "VerifyGoal",
            "VM": "VerifyMultiGoal",
        }

        type_name = type_colors.get(node_type, "Unknown")
        print(f"  [{i:2d}] ID:{node:3d} Type:{type_name:12s} Info:{repr(node_data)}")

    print("=" * 60)


# ******************************************    Demo / Test Routine         ****************************************** #
if __name__ == "__main__":
    raise NotImplementedError("Test run / Demo routine for plotter isn't implemented.")

"""
Author(s): Yash Bansod
Repository: https://github.com/YashBansod/IPyHOP
"""
